with Miniparser.Language_Spec; use Miniparser.Language_Spec;

package Miniparser.Parser is

   --  Parse a source string using the given language specification.
   --
   --  This is a fairly straightforward implementation of an LR(1) parser.
   --  It takes a language specification (LS) and a string to parse (Source).
   --  The string is tokenized via Miniparser.Lexer.Lex and then parsed
   --  according to the ACTION/GOTO tables in LS into a syntax tree, which
   --  is returned.
   --
   --  If LS does not yet have parse tables (Has_Parse = False), Build_LS is
   --  called automatically to generate them.
   --
   --  During reduction, nodes are filtered according to LS.Simplify (flatten
   --  children into parent), LS.Aggregate (flatten consecutive same-type
   --  nodes), and LS.Remove (discard entirely).  Symbols whose names start
   --  with '_' (generated by repetition/optional expansion) are also
   --  simplified.
   --
   --  Parameters:
   --    LS        — Language specification (may be modified to add parse
   --                tables on first call).
   --    Source    — The input string to parse.
   --    Verbosity — Diagnostic output level.  0 = silent.  3+ = state/action
   --                tracing.  4+ = symbol stack summary.  5+ = full stack.
   --
   --  Returns the root AST_Node_Access of the parse tree.
   --
   --  Raises Parser_Syntax_Error on unexpected tokens or unexpected end of
   --  input.  Raises Parser_Internal_Error on internal inconsistencies
   --  (missing GOTO entries, unexpected final stack state).
   function Parse
     (LS        : in out Language_Spec_Record;
      Source    : String;
      Verbosity : Natural := 0) return AST_Node_Access;

   --  Raised when the input does not conform to the grammar.
   Parser_Syntax_Error  : exception;

   --  Raised on internal parser inconsistencies (should not occur with a
   --  correct grammar and correct parser implementation).
   Parser_Internal_Error : exception;

end Miniparser.Parser;
